CREATE TABLE T_LOCATION
  ( CODE VARCHAR(6) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EN_NAME VARCHAR(200),
    RANK VARCHAR(1) NOT NULL,
    LEVEL_CODE VARCHAR(40),
    PARENT_CODE VARCHAR(6),
    STATUS VARCHAR(1) NOT NULL, 
    POST_CODE VARCHAR(6),
    DIALING_CODE VARCHAR(6),
    REMARK VARCHAR(100),
    CREATE_TIME DATETIME NOT NULL,
    UPDATE_TIME DATETIME NOT NULL,
    PRIMARY KEY(CODE)
  );

CREATE INDEX IDX_T_LOCATION_01 ON T_LOCATION (CODE);
CREATE INDEX IDX_T_LOCATION_02 ON T_LOCATION (RANK,NAME);
