package com.hefei.api.rms.client;

import org.apache.log4j.Logger;

import com.hefei.common.http.client.ServiceUrlConstants;
import com.hefei.common.util.ConfigReader;

public class RmsUrlConstants  extends ServiceUrlConstants{

	private static final Logger log = Logger.getLogger(RmsUrlConstants.class);
	public static final String CONFIG_FILE_NAME_CONF = "rms-server-url-conf";

	public static String RMS_SERVER_COMPANY_REG_CREATE_COMPANY_EMPLOYEE = null;
	public static String RMS_SERVER_COMPANY_CREATE = null;
	public static String RMS_SERVER_COMPANY_UPDATE = null;
	public static String RMS_SERVER_COMPANY_GETBYCOMPANYID = null;
	public static String RMS_SERVER_COMPANY_GETBYUSERID = null;
	public static String RMS_SERVER_COMPANY_GETBYEMPLOYEEID = null;
	public static String RMS_SERVER_COMPANY_FIND_MANAGED_PAGINATION = null;
	
	public static String RMS_SERVER_COMPANY_GET_INDUSTRY = null;
	/** 保存员工奖惩信息 */
	public static String RMSCLIENT_SERVER_BEHAVIOR_SAVE = null;
	/** 更新员工奖惩信息 */
	public static String RMSCLIENT_SERVER_BEHAVIOR_UPDATE = null;
	/** 查找员工奖惩信息 */
	public static String RMSCLIENT_SERVER_BEHAVIOR_FIND = null;
	/** 查询员工社保信息 */
	public static String RMSCLIENT_SERVER_SECURITY_FIND = null;
	/** 保存员工社保信息 */
	public static String RMSCLIENT_SERVER_SECURITY_SAVE = null;
	/** 调整员工社保信息 */
	public static String RMSCLIENT_SERVER_SECURITY_ADJUST = null;
	/** 社保发放 */
	public static String RMSCLIENT_SERVER_SECURITY_GRANT = null;
	/** 查询保险信息 */
	public static String RMSCLIENT_SERVER_INSURANCE_FIND = null;
	/** 保存保险信息 */
	public static String RMSCLIENT_SERVER_INSURANCE_SAVE = null;
	/** 更新保险信息*/
	public static String RMSCLIENT_SERVER_INSURANCE_UPDATE = null;
	/** 查询体检信息 */
	public static String RMSCLIENT_SERVER_PHYSICAL_FIND = null;
	/** 保存体检信息 */
	public static String RMSCLIENT_SERVER_PHYSICAL_SAVE = null;
	/** 更新体检信息*/
	public static String RMSCLIENT_SERVER_PHYSICAL_UPDATE = null;
	/** 查询员工信息 列表*/
	public static String RMSCLIENT_SERVER_EMPLOYEE_FIND_PAGINATION = null;
	/** 保存员工信息 */
	public static String RMSCLIENT_SERVER_EMPLOYEE_SAVE = null;
	/** 更新员工信息*/
	public static String RMSCLIENT_SERVER_EMPLOYEE_UPDATE = null;
	/** 查找员工信息*/
	public static String RMSCLIENT_SERVER_EMPLOYEE_GET_BY_ID = null;
	
	public static String RMSCLIENT_SERVER_EMPLOYEE_GET_BY_EMP_COM_ID = null;
	
	public static String RMSCLIENT_SERVER_EMPLOYEE_GET_BY_IDNO = null;
	
	public static String RMSCLIENT_SERVER_EMPLOYEE_GET_BY_USERID = null;
	public static String RMSCLIENT_SERVER_EMPLOYEE_GET_DEPARTMENT_POSITION = null;
	public static String RMSCLIENT_SERVER_EMPLOYEE_UPDATE_DEPARTMENT_POSITION = null;
	public static String RMSCLIENT_SERVER_EMPLOYEE_GRANT_POSITION = null;
	/**保存岗位**/
	public static String RMSCLIENT_SERVER_POSITION_SAVE = null;
	/**更新岗位**/
	public static String RMSCLIENT_SERVER_POSITION_UPDATE = null;
	/**查看岗位信息**/
	public static String RMSCLIENT_SERVER_POSITION_GET_BY_DEPARTMENT = null;
	
	public static String RMSCLIENT_SERVER_POSITION_GET_BY_ID = null;
	/**保存部门**/
	public static String RMSCLIENT_SERVER_DEPARTMENT_SAVE = null;
	/**更新部门**/
	public static String RMSCLIENT_SERVER_DEPARTMENT_UPDATE = null;
	/**查看部门**/
	public static String RMSCLIENT_SERVER_DEPARTMENT_GET_BY_ID = null;
	
	public static String RMSCLIENT_SERVER_DEPARTMENT_FIND_DEPARTMENT_PAGINATION_BY_COMPANY = null;
	/**保存面试信息**/
	public static String RMSCLIENT_SERVER_INTERVIEW_SAVE = null;
	/**更新面试信息**/
	public static String RMSCLIENT_SERVER_INTERVIEW_UPDATE = null;
	/**查看面试信息**/
	public static String RMSCLIENT_SERVER_INTERVIEW_FIND = null;
	/**保存合同信息**/
	public static String RMSCLIENT_SERVER_CONTRACT_SAVE = null;
	/**更新合同信息**/
	public static String RMSCLIENT_SERVER_CONTRACT_UPDATE = null;
	/**查看合同信息**/
	public static String RMSCLIENT_SERVER_CONTRACT_FIND = null;
	/**保存出勤信息**/
	public static String RMSCLIENT_SERVER_ATTENDANCE_CREATE = null;
	/**更新出勤信息**/
	public static String RMSCLIENT_SERVER_ATTENDANCE_UPDATE = null;
	/**查看出勤信息**/
	public static String RMSCLIENT_SERVER_ATTENDANCE_FIND = null;
	
	public static String RMSCLIENT_SERVER_LEAVE_FIND_PAGINATION = null;
	public static String RMSCLIENT_SERVER_LEAVE_APPLY = null;
	public static String RMSCLIENT_SERVER_LEAVE_AUDIT = null;
	public static String RMSCLIENT_SERVER_LEAVE_GET_BY_ID = null;
	
	
	public static String RMSCLIENT_SERVER_SALARY_GET = null;
	public static String RMSCLIENT_SERVER_SALARY_TRANSACTION_GET = null;
	public static String RMSCLIENT_SERVER_SALARY_ADJUST = null;
	public static String RMSCLIENT_SERVER_SALARY_TRANSACTION_ADJUST = null;
	public static String RMSCLIENT_SERVER_SALARY_FIND_PAGINATION = null;
	public static String RMSCLIENT_SERVER_SALAY_HISTORY_FIND_PAGINATION = null;
	public static String RMSCLIENT_SERVER_SALARY_TRANSACTION_FIND_PAGINATION = null;
	public static String RMSCLIENT_SERVER_SALARY_TRANSACTION_GENERATE = null;
	public static String RMSCLIENT_SERVER_SALARY_TRANSACTION_PAY = null;
	
	public static String RMSCLIENT_SERVER_SS_GET = null;
	public static String RMSCLIENT_SERVER_SS_TRANSACTION_GET = null;
	public static String RMSCLIENT_SERVER_SS_ADJUST = null;
	public static String RMSCLIENT_SERVER_SS_TRANSACTION_ADJUST = null;
	public static String RMSCLIENT_SERVER_SS_TRANSACTION_PAY = null;
	
	public void init(String configFileName){
		try{
			ConfigReader reader = ConfigReader.read(configFileName);
			RMSCLIENT_SERVER_BEHAVIOR_SAVE = reader.getConstant("RMSCLIENT_SERVER_BEHAVIOR_SAVE");
			RMSCLIENT_SERVER_BEHAVIOR_FIND = reader.getConstant("RMSCLIENT_SERVER_BEHAVIOR_FIND");
			RMSCLIENT_SERVER_SECURITY_FIND = reader.getConstant("RMSCLIENT_SERVER_SECURITY_FIND");
			RMSCLIENT_SERVER_BEHAVIOR_UPDATE = reader.getConstant("RMSCLIENT_SERVER_BEHAVIOR_UPDATE");
			RMSCLIENT_SERVER_SECURITY_SAVE = reader.getConstant("RMSCLIENT_SERVER_SECURITY_SAVE");
			RMSCLIENT_SERVER_SECURITY_ADJUST = reader.getConstant("RMSCLIENT_SERVER_SECURITY_ADJUST");
			RMSCLIENT_SERVER_SECURITY_GRANT = reader.getConstant("RMSCLIENT_SERVER_SECURITY_GRANT");
			RMSCLIENT_SERVER_INSURANCE_FIND = reader.getConstant("RMSCLIENT_SERVER_INSURANCE_FIND");
			RMSCLIENT_SERVER_INSURANCE_SAVE = reader.getConstant("RMSCLIENT_SERVER_INSURANCE_SAVE");
			RMSCLIENT_SERVER_INSURANCE_UPDATE = reader.getConstant("RMSCLIENT_SERVER_INSURANCE_UPDATE");
			RMSCLIENT_SERVER_PHYSICAL_FIND = reader.getConstant("RMSCLIENT_SERVER_PHYSICAL_FIND");
			RMSCLIENT_SERVER_PHYSICAL_SAVE = reader.getConstant("RMSCLIENT_SERVER_PHYSICAL_SAVE");
			RMSCLIENT_SERVER_PHYSICAL_UPDATE = reader.getConstant("RMSCLIENT_SERVER_PHYSICAL_UPDATE");
			
			RMSCLIENT_SERVER_EMPLOYEE_FIND_PAGINATION = reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_FIND_PAGINATION");
			RMSCLIENT_SERVER_EMPLOYEE_SAVE = reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_SAVE");
			RMSCLIENT_SERVER_EMPLOYEE_UPDATE = reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_UPDATE");
			RMSCLIENT_SERVER_EMPLOYEE_GET_BY_ID = reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_GET_BY_ID");
			RMSCLIENT_SERVER_EMPLOYEE_GET_BY_IDNO= reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_GET_BY_IDNO");
			RMSCLIENT_SERVER_EMPLOYEE_GET_BY_EMP_COM_ID = reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_GET_BY_EMP_COM_ID");
			RMSCLIENT_SERVER_EMPLOYEE_GET_BY_USERID= reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_GET_BY_USERID");
			RMSCLIENT_SERVER_EMPLOYEE_GET_DEPARTMENT_POSITION= reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_GET_DEPARTMENT_POSITION");
			RMSCLIENT_SERVER_EMPLOYEE_UPDATE_DEPARTMENT_POSITION= reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_UPDATE_DEPARTMENT_POSITION");
			RMSCLIENT_SERVER_EMPLOYEE_GRANT_POSITION= reader.getConstant("RMSCLIENT_SERVER_EMPLOYEE_GRANT_POSITION");
			
			RMSCLIENT_SERVER_POSITION_SAVE = reader.getConstant("RMSCLIENT_SERVER_POSITION_SAVE");
			RMSCLIENT_SERVER_POSITION_UPDATE = reader.getConstant("RMSCLIENT_SERVER_POSITION_UPDATE");
			RMSCLIENT_SERVER_POSITION_GET_BY_ID = reader.getConstant("RMSCLIENT_SERVER_POSITION_GET_BY_ID");
			RMSCLIENT_SERVER_POSITION_GET_BY_DEPARTMENT = reader.getConstant("RMSCLIENT_SERVER_POSITION_GET_BY_DEPARTMENT");
			
			RMSCLIENT_SERVER_DEPARTMENT_SAVE  = reader.getConstant("RMSCLIENT_SERVER_DEPARTMENT_SAVE");
			RMSCLIENT_SERVER_DEPARTMENT_UPDATE  = reader.getConstant("RMSCLIENT_SERVER_DEPARTMENT_UPDATE");
			RMSCLIENT_SERVER_DEPARTMENT_GET_BY_ID  = reader.getConstant("RMSCLIENT_SERVER_DEPARTMENT_GET_BY_ID");
			RMSCLIENT_SERVER_DEPARTMENT_FIND_DEPARTMENT_PAGINATION_BY_COMPANY  = reader.getConstant("RMSCLIENT_SERVER_DEPARTMENT_FIND_DEPARTMENT_PAGINATION_BY_COMPANY");
			
			RMSCLIENT_SERVER_INTERVIEW_SAVE  = reader.getConstant("RMSCLIENT_SERVER_INTERVIEW_SAVE");
			RMSCLIENT_SERVER_INTERVIEW_UPDATE  = reader.getConstant("RMSCLIENT_SERVER_INTERVIEW_UPDATE");
			RMSCLIENT_SERVER_INTERVIEW_FIND  = reader.getConstant("RMSCLIENT_SERVER_INTERVIEW_FIND");
			RMSCLIENT_SERVER_CONTRACT_SAVE  = reader.getConstant("RMSCLIENT_SERVER_CONTRACT_SAVE");
			RMSCLIENT_SERVER_CONTRACT_UPDATE  = reader.getConstant("RMSCLIENT_SERVER_CONTRACT_UPDATE");
			RMSCLIENT_SERVER_CONTRACT_FIND  = reader.getConstant("RMSCLIENT_SERVER_CONTRACT_FIND");
			RMSCLIENT_SERVER_ATTENDANCE_CREATE  = reader.getConstant("RMSCLIENT_SERVER_ATTENDANCE_CREATE");
			RMSCLIENT_SERVER_ATTENDANCE_UPDATE  = reader.getConstant("RMSCLIENT_SERVER_ATTENDANCE_UPDATE");
			RMSCLIENT_SERVER_ATTENDANCE_FIND  = reader.getConstant("RMSCLIENT_SERVER_ATTENDANCE_FIND");
			
			RMS_SERVER_COMPANY_REG_CREATE_COMPANY_EMPLOYEE  = reader.getConstant("RMS_SERVER_COMPANY_REG_CREATE_COMPANY_EMPLOYEE");
			RMS_SERVER_COMPANY_CREATE  = reader.getConstant("RMS_SERVER_COMPANY_CREATE");
			RMS_SERVER_COMPANY_UPDATE  = reader.getConstant("RMS_SERVER_COMPANY_UPDATE");
			RMS_SERVER_COMPANY_GETBYCOMPANYID  = reader.getConstant("RMS_SERVER_COMPANY_GETBYCOMPANYID");
			RMS_SERVER_COMPANY_GETBYUSERID  = reader.getConstant("RMS_SERVER_COMPANY_GETBYUSERID");
			RMS_SERVER_COMPANY_GETBYEMPLOYEEID  = reader.getConstant("RMS_SERVER_COMPANY_GETBYEMPLOYEEID");
			RMS_SERVER_COMPANY_FIND_MANAGED_PAGINATION = reader.getConstant("RMS_SERVER_COMPANY_FIND_MANAGED_PAGINATION");
			RMS_SERVER_COMPANY_GET_INDUSTRY = reader.getConstant("RMS_SERVER_COMPANY_GET_INDUSTRY");
			
			RMSCLIENT_SERVER_LEAVE_FIND_PAGINATION = reader.getConstant("RMSCLIENT_SERVER_LEAVE_FIND_PAGINATION");
			RMSCLIENT_SERVER_LEAVE_APPLY = reader.getConstant("RMSCLIENT_SERVER_LEAVE_APPLY");
			RMSCLIENT_SERVER_LEAVE_AUDIT = reader.getConstant("RMSCLIENT_SERVER_LEAVE_AUDIT");
			RMSCLIENT_SERVER_LEAVE_GET_BY_ID = reader.getConstant("RMSCLIENT_SERVER_LEAVE_GET_BY_ID");
			
			
			RMSCLIENT_SERVER_SALARY_GET = reader.getConstant("RMSCLIENT_SERVER_SALARY_GET");
			RMSCLIENT_SERVER_SALARY_TRANSACTION_GET = reader.getConstant("RMSCLIENT_SERVER_SALARY_TRANSACTION_GET");
			RMSCLIENT_SERVER_SALARY_ADJUST = reader.getConstant("RMSCLIENT_SERVER_SALARY_ADJUST");
			RMSCLIENT_SERVER_SALARY_TRANSACTION_ADJUST = reader.getConstant("RMSCLIENT_SERVER_SALARY_TRANSACTION_ADJUST");
			RMSCLIENT_SERVER_SALARY_FIND_PAGINATION = reader.getConstant("RMSCLIENT_SERVER_SALARY_FIND_PAGINATION");
			RMSCLIENT_SERVER_SALAY_HISTORY_FIND_PAGINATION = reader.getConstant("RMSCLIENT_SERVER_SALAY_HISTORY_FIND_PAGINATION");
			RMSCLIENT_SERVER_SALARY_TRANSACTION_FIND_PAGINATION = reader.getConstant("RMSCLIENT_SERVER_SALARY_TRANSACTION_FIND_PAGINATION");
			RMSCLIENT_SERVER_SALARY_TRANSACTION_GENERATE = reader.getConstant("RMSCLIENT_SERVER_SALARY_TRANSACTION_GENERATE");
			RMSCLIENT_SERVER_SALARY_TRANSACTION_PAY = reader.getConstant("RMSCLIENT_SERVER_SALARY_TRANSACTION_PAY");
			
			RMSCLIENT_SERVER_SS_GET = reader.getConstant("RMSCLIENT_SERVER_SS_GET");
			RMSCLIENT_SERVER_SS_TRANSACTION_GET = reader.getConstant("RMSCLIENT_SERVER_SS_TRANSACTION_GET");
			RMSCLIENT_SERVER_SS_ADJUST = reader.getConstant("RMSCLIENT_SERVER_SS_ADJUST");
			RMSCLIENT_SERVER_SS_TRANSACTION_ADJUST = reader.getConstant("RMSCLIENT_SERVER_SS_TRANSACTION_ADJUST");
			RMSCLIENT_SERVER_SS_TRANSACTION_PAY = reader.getConstant("RMSCLIENT_SERVER_SS_TRANSACTION_PAY");
		}catch(Exception e){
			log.error("UrlConstants init exception", e);
			System.exit(0);
		}
		
	}
}
